config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: "register"}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolio/react_on_rails', to: 'portfolios#react_on_rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
		has_many :technologies
		accepts_nested_attributes_for :technologies, reject_if: :all_blank, allow_destroy: true

		include Placeholder
	  validates_presence_of :title, :body, :main_image, :thumb_image

	  scope :for_subtitile, -> (subtitle) { where('subtitle = ?', subtitle) }
	  scope :by_position, -> { order('position ASC') }
	  # scope :for_subtitile, -> (subtitle) { where(subtitle: subtitle) }
	  # def self.react_on_rails
	  # 	where(subtitle: "React On Rails")
	  # end

	  scope :for_ruby_on_rails, -> { where(subtitle: "Ruby On Rails") }

	  after_initialize :set_defaults

	  def set_defaults
	  	self.main_image ||= Placeholder.image_generator(600,400)
	  	self.thumb_image ||= Placeholder.image_generator(350,200)
	  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
  layout 'portfolio'
  access all: [:show, :index], user: {except: [:destroy, :create, :new, :update, :edit, :sort]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    head :ok
  end

  def react_on_rails
    @portfolio_items_react_on_rails = Portfolio.all.for_subtitile("React On Rails")
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(protfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    3.times { @portfolio_item.technologies.build }
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(protfolio_params)
        format.html { redirect_to portfolios_path, notice: 'The record successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    # Perform the lookup in the before action

    # Destroy/delete the record
    @portfolio_item.destroy

    # Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was removed.' }
    end
  end

  private

  def set_portfolio_item
    @portfolio_item =  Portfolio.find(params[:id])
  end

  def protfolio_params 
    params.require(:portfolio).permit( :title, :subtitle, :body, technologies_attributes: [ :name ] )
  end

end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio_item) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control", rows: 4.5 %>
      </div>
    </div>
  </div>
  
  <h2>Technologies Used:</h2>
  <div>
    <%= f.fields_for :technologies do |technology_form| %>
      <div class="form-group">
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name, class: "form-control" %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.submit " Save Portfolio Item", class: "btn btn-primary btn-block"%>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="card" data-id="<%= portfolio_item.id %>">
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <p class="card-text">
    <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> <%= portfolio_item.subtitle %>
  </p>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
	<h1>Edit this Portfolio Item</h1>
	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row <%= sortable if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
	<h1>Create a new Portfolio Item</h1>
	<%= render "form", portfolio_item: @portfolio_item %>	
</div>

app/views/portfolios/react_on_rails.html.erb
<h1>React on Rails Items</h1>

<%= link_to "Create New Item", new_portfolio_url if logged_in?(:admin, :customer, :etc) %>

<% @portfolio_items_react_on_rails.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:admin, :customer, :etc)%>
  <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:admin, :customer, :etc)%>
<% end %>

app/views/portfolios/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-7">
			<%= image_tag @portfolio_item.main_image %>
		</div>
		<div class="col md-5">
			<h1><%= @portfolio_item.title %></h1>
			<em><%= @portfolio_item.subtitle %></em>
			<p><%= @portfolio_item.body %></p>
			<h2>Technologies Used:</h2>
			<% @portfolio_item.technologies.each do |techs| %>
				<p><%= techs.name %></p>
			<% end %>
		</div>
	</div>
</div>